-- V60: 扩展账户流水操作类型 — Wave 11 基础设施层
-- 更新 operation_type 列注释以包含新增的 8 种操作类型
-- 新增类型：CLEARING_SETTLE/SETTLEMENT_TRANSFER/RECON_ADJUST/SUSPENSE_WRITEOFF/RISK_FREEZE/RISK_UNFREEZE/AUTO_WITHDRAW/RESERVE_REPLENISH

ALTER TABLE account_transactions
    MODIFY COLUMN operation_type VARCHAR(32) NOT NULL
    COMMENT '操作类型: DEPOSIT/WITHDRAW/FREEZE/UNFREEZE/TRANSFER/PAYMENT/REFUND/VOID_REVERSE/REVERSAL_ADJUST/ESCROW_FREEZE/ESCROW_RELEASE/PREAUTH_FREEZE/PREAUTH_CAPTURE/PREAUTH_RELEASE/CLEARING_SETTLE/SETTLEMENT_TRANSFER/RECON_ADJUST/SUSPENSE_WRITEOFF/RISK_FREEZE/RISK_UNFREEZE/AUTO_WITHDRAW/RESERVE_REPLENISH';