apiVersion: v2
name: nexus-core
description: NexusChain 结算链节点（DPoS/PoS 共识、P2P gRPC、RPC、存储）
type: application
version: 2.2.0
appVersion: "2.2.0"
keywords:
  - blockchain
  - dpos
  - pos
  - grpc
  - settlement
home: https://github.com/nexus/NexusChain
sources:
  - https://github.com/nexus/NexusChain
maintainers:
  - name: NexusChain DevOps
    email: devops@nexus.network
