plugins {
    id 'java'
}

group 'org.nexus'
version '1.0-SNAPSHOT'

sourceCompatibility = 17

repositories {
    maven {
        url 'https://maven.aliyun.com/nexus/content/groups/public/'
    }
    maven {
        url 'https://maven.aliyun.com/nexus/content/repositories/jcenter'
    }
    mavenCentral()
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
// https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    testImplementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    compileOnly "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.google.guava:guava:${guavaVersion}"

    implementation "commons-codec:commons-codec:${commonsCodecVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}
