apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# staging overlay
# 配套：helm template deploy/helm/ -f values-staging.yaml
#   | kubectl kustomize deploy/kustomize/overlays/staging
resources:
  - ../../base

namespace: nexus-staging

labels:
  - includeSelectors: false
    pairs:
      nexus-chain.io/env: staging
