-- V8: merchant_keypairs 表（B-14 修复：VaultKeyManager 密钥持久化，PostgreSQL 版本）。
--
-- 由 V13__merchant_keypairs.sql（MySQL/H2 语法）转换而来，供 prod profile 使用
-- （Flyway locations=classpath:db/migration-pg）。语义与 V13 完全一致，仅语法适配：
--   * AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY（PostgreSQL 标准语法）
--   * TIMESTAMP 精度保持默认（PostgreSQL TIMESTAMP 等价于 MySQL TIMESTAMP）
--   * CONSTRAINT name UNIQUE (cols) 语法两边兼容，保持一致
--
-- 背景：VaultKeyManager 原先将 AES-256-GCM 加密后的商户密钥对仅保存在内存
-- ConcurrentHashMap 中，服务重启后所有商户密钥丢失，导致商户无法认证。
-- 本表将加密后的密钥对落库，启动时全量加载回内存，写入时同步 upsert。
CREATE TABLE IF NOT EXISTS merchant_keypairs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    encrypted_keypair VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_merchant_keypairs_merchant_id UNIQUE (merchant_id)
);