// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consortium.proto

package org.nexus.consortium.proto;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ping)
    com.google.protobuf.MessageOrBuilder {
}
